name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: WEB3_HTTP_ENDPOINT=https://foo.bar. npm test

      - name: Lint code
        run: npm run lint:ci

      - name: Run e2e tests
        run: WEB3_HTTP_ENDPOINT=${{ secrets.WEB3_HTTP_ENDPOINT }} npm run test:e2e
